### ISSUE TITLE
Add silverstripe/session-manager

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/recipe-cms#47]
On enhancing the [session-manager module](https://github.com/silverstripe/silverstripe-session-manager), it's something that's likely to provide broad benefit and is almost a baseline feature for any CMS or tool where software users manage their profile.

When considering the path of least resistance on making this module available to projects, this recipe was considered the best place to add it. 

Other options that were considered were, from widest distribution to least distribution:
a) require as part of silverstripe/admin (aka "add it to core")
b) require as part of silverstripe/recipe-cms (not recipe-core, that does not include admin)
c) require as part of silverstripe/installer
d) require as part of silverstripe/silverstripe-security-extensions (not even sure what uses this?)
e) manually add to project (this is always an option)

### Questions of stability

The silverstripe/session-manager module has been out in the wild for some time with a 0.x tag while early testing and feedback is sought. 

We've been managing a bit of testing and user feedback internally, which will help us confirm confidence in tagging the module as stable and including it in this recipe.

### Implementation tasks
Tasks required as part of this issue could be:
- [x] Tag the module as stable
- [x] Add the module to recipe-cms
- [x] Tag session-manager version 1.1.0 when all PR's merged and create 1.1 branch
- [x] After PR adding module to recipe-cms has been merged, ensure that session-manager pre-stable is removed from project skeleton
- [x] Ensure the next changelog reflects this change
- [x] Move userhelp docs into core (and out of the 'optional modules' section). See: https://github.com/silverstripe/silverstripe-session-manager/issues/85

### PRs - update unit tests to use logInAs()
- [x] https://github.com/silverstripe/silverstripe-admin/pull/1245
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1230
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2679
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10052
- [x] https://github.com/silverstripe/silverstripe-versioned/pull/340

### PRs - follow up
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2682
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10073
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10066
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10061

### PR - update recipe-cms
- [x] https://github.com/silverstripe/recipe-cms/pull/48 (merge after PRs above)

### PRs - Docs
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10042
- [x] https://github.com/silverstripe/silverstripe-session-manager/pull/86
- [x] https://github.com/silverstripe/silverstripe-userhelp-content/pull/164

### PRs - Sink (remember to merge-up)
- [x] https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/50

### SwiftMailer v6 not allowing spaces at start or end of email addresses
- (not session-manager though still breaking sink)
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10065

### TODO
- Probably skip some framework tests related to RememberLoginHash if session-manager is present and rely on the session-manager unit tests instead - see comment below

**Comment by emteknetnz** [comment]
https://travis-ci.com/github/silverstripe/silverstripe-installer/jobs/532576643
-  SilverStripe\Control\Tests\ControllerTest::testAllowedActions - disabling session-manager appeared to make no difference
-All other tests - disabling session-manager fixed issue

https://travis-ci.com/github/silverstripe/cwp-recipe-kitchen-sink/jobs/532563590

https://travis-ci.com/github/silverstripe/cwp-recipe-kitchen-sink/jobs/532563593

https://travis-ci.com/github/silverstripe/cwp-recipe-kitchen-sink/jobs/532563602
